name: k6 Load Tests with Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Postman-to-k6
        run: npm install -g postman-to-k6

      - name: Set up k6
        uses: grafana/setup-k6-action@v1

      - name: Convert Postman collections to k6 scripts
        run: |
          for file in postman/collections/*.json; do
            filename=$(basename "$file" .json)
            # Include environment files in the conversion if they exist
            env_files=""
            for env_file in postman/environments/*.json; do
              env_files+=" -e $env_file"
            done
            postman-to-k6 "$file" $env_files -o "k6-test/${filename}-script.js"
          done

      - name: Verify k6-test directory
        run: ls -la k6-test

      - name: Combine k6 scripts
        run: |
          node k6-test/combine-scripts.js
        env:
          NODE_ENV: development

      - name: Run combined k6 load test and generate HTML report
        run: |
          k6 run --vus 2 --duration 1m k6-test/combined-k6-script.js
        env:
          K6_OUTPUT: html=k6-test/summary.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: k6-summary-report
          path: k6-test/summary.html
