name: k6 Load Tests with HTML Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install postman-to-k6
        run: npm install -g postman-to-k6

      - name: Set up k6
        uses: grafana/setup-k6-action@v1

      - name: Convert Postman collections to k6 scripts
        run: |
          mkdir -p k6-test
          for file in postman/collections/*.json; do
            filename=$(basename "$file" .json)
            env_files=""
            for env_file in postman/environments/*.json; do
              env_files+=" -e $env_file"
            done
            postman-to-k6 "$file" $env_files -o "k6-test/${filename}-script.js"
          done

      - name: List files in k6-test directory
        run: ls -R k6-test

      - name: Verify core.js file path
        run: |
          if [ ! -f k6-test/libs/shim/core.js ]; then
            echo "Error: k6-test/libs/shim/core.js file not found!"
            exit 1
          fi

      - name: Combine k6 scripts with template
        run: |
          for script in k6-test/*-script.js; do
            cat k6-script-template.js "$script" > combined-k6-script.js
            k6 run --vus 5 --duration 30s combined-k6-script.js
          done

      - name: Upload HTML reports as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: k6-html-reports
          path: summary.html
