name: k6 Load Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g postman-to-k6 k6-html-reporter

      - name: Set up k6
        uses: grafana/setup-k6-action@v1

      - name: Convert Postman collections to k6 scripts
        run: |
          mkdir -p k6-test
          for file in postman/collections/*.json; do
            filename=$(basename "$file" .json)
            # Include environment files in the conversion if they exist
            env_files=""
            for env_file in postman/environments/*.json; do
              env_files+=" -e $env_file"
            done
            postman-to-k6 "$file" $env_files -o "k6-test/${filename}-script.js"
          done

      - name: Combine k6 script with template
        run: |
          node combine-scripts.js

      - name: Run k6 load tests and generate JSON results
        run: |
          mkdir -p k6-results
          for script in k6-test/*-script.js; do
            output_file="k6-results/$(basename "$script" -script.js).json"
            k6 run --vus 5 --duration 30s "$script" --out json="$output_file"
          done

      - name: Generate HTML reports
        run: |
          mkdir -p k6-reports
          for result in k6-results/*.json; do
            output_html="k6-reports/$(basename "$result" .json).html"
            k6-html-reporter "$result" -o "$output_html"
          done
