name: k6 Load Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install postman-to-k6
        run: npm install -g postman-to-k6

      - name: Set up k6
        uses: grafana/setup-k6-action@v1

      - name: Convert Postman collections to k6 scripts
        run: |
          mkdir -p k6-test
          for collection in postman/collections/*.json; do
            filename=$(basename "$collection" .json)
            environment_file="postman/environment/${filename}-environment.json"
            if [ -f "$environment_file" ]; then
              postman-to-k6 "$collection" -e "$environment_file" -o "k6-test/${filename}-script.js"
            else
              postman-to-k6 "$collection" -o "k6-test/${filename}-script.js"
            fi
            # Debug output of the generated k6 script
            echo "Generated k6 script for $collection:"
            cat "k6-test/${filename}-script.js"
          done

      - name: Log in to k6 Cloud
        env:
          K6_API_TOKEN: ${{ secrets.K6_API_TOKEN }}
        run: k6 login cloud --token "${K6_API_TOKEN}"

      - name: Run k6 load tests on k6 Cloud
        env:
          K6_API_TOKEN: ${{ secrets.K6_API_TOKEN }}
        run: |
          for script in k6-test/*-script.js; do
            echo "Running k6 test script: $script"
            k6 cloud --vus 5 --duration 30s "$script"
          done
