name: k6 Load Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install postman-to-k6
        run: npm install -g postman-to-k6

      - name: Set up k6
        uses: grafana/setup-k6-action@v1

      - name: Create k6 test directory
        run: mkdir -p "${{ github.workspace }}/k6-test"

      - name: Convert Postman collections and environment to k6 scripts
        run: |
          for file in "${{ github.workspace }}/postman/collections/"*.json; do
            if [ -f "$file" ]; then
              filename=$(basename "$file" .json)
              postman-to-k6 --collection "$file" --env "${{ github.workspace }}/postman/environments/env.json" -o "${{ github.workspace }}/k6-test/${filename}-script.js"
            else
              echo "No JSON files found in ${GITHUB_WORKSPACE}/postman/collections"
            fi
          done

      - name: Run k6 load tests
        run: |
          for script in "${{ github.workspace }}/k6-test/"*-script.js; do
            if [ -f "$script" ]; then
              k6 run --vus 5 --duration 30s "$script"
            else
              echo "No k6 scripts found in ${GITHUB_WORKSPACE}/k6-test"
            fi
          done

     
