name: k6 Tests Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install postman-to-k6
        run: npm install -g postman-to-k6

      - name: Set up k6
        uses: grafana/setup-k6-action@v1

      - name: Convert Postman collections to k6 scripts
        run: |
          mkdir -p k6-test
          for file in postman/collections/*.json; do
            filename=$(basename "$file" .json)
            postman-to-k6 "$file" -o "k6-test/${filename}-script.js"
          done

      - name: Find and extract environment variables from JSON file
        id: extract_env
        run: |
          # Find the environment JSON file
          ENV_FILE=$(find postman/collections -name '*_environment.json' | head -n 1)
          if [ -z "$ENV_FILE" ]; then
            echo "No environment JSON file found."
            exit 1
          fi
          echo "Using environment file: $ENV_FILE"
          # Extract variables from the JSON file
          jq -r '.values[] | "\(.key)=\(.value)"' "$ENV_FILE" > .env

      - name: Load environment variables
        env:
          # Load environment variables from the .env file
          $(cat .env | xargs)
        run: |
          for script in k6-test/*-script.js; do
            k6 run --vus 5 --duration 30s "$script"
          done
