name: Newman Test Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Newman and htmlextra reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Create Newman report directory
        run: mkdir -p "${{ github.workspace }}/newman"

      - name: Run API tests with Newman
        run: |
          echo "Running tests with Newman"
          collection_id="37647624-eaaa4e31-0144-4fa4-9e86-d5d9e005997d"
          environment_id="37647624-c0d8b51d-ed2b-43e6-9821-af0d2fe840e0"
          
          newman run $collection_id \
            --environment $environment_id \
            --reporters cli,htmlextra,json \
            --reporter-htmlextra-export "${{ github.workspace }}/newman/report-$(basename "$collection_id").html" \
            --reporter-json-export "${{ github.workspace }}/newman/report-$(basename "$collection_id").json"

      - name: Upload Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: "${{ github.workspace }}/newman/"
