name: Newman Test Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Newman and htmlextra reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Create Newman report directory
        run: mkdir -p "${{ github.workspace }}/newman"

      - name: Run API tests with Newman
        run: |
          echo "Looking for files in ${GITHUB_WORKSPACE}/postman/collections"
          for file in "${GITHUB_WORKSPACE}/postman/collections/"*.json; do
            if [ -f "$file" ]; then
              echo "Running tests for $file"
              # Find environment files
              for env_file in "${GITHUB_WORKSPACE}/postman/environments/"*.json; do
                if [ -f "$env_file" ]; then
                  newman run "$file" \
                    --environment "$env_file" \
                    --reporters cli,htmlextra,json \
                    --reporter-htmlextra-export "${{ github.workspace }}/newman/report-$(basename "$file" .json).html" \
                    --reporter-json-export "${{ github.workspace }}/newman/report-$(basename "$file" .json).json"
                else
                  echo "No environment files found in ${GITHUB_WORKSPACE}/postman/environments"
                fi
              done
            else
              echo "No JSON files found in ${GITHUB_WORKSPACE}/postman/collections"
            fi
          done

      - name: Create artifacts folder
        run: mkdir -p "${{ github.workspace }}/artifacts"

      - name: Move reports to artifacts folder
        run: mv "${{ github.workspace }}/newman/*" "${{ github.workspace }}/artifacts/"

      - name: Upload Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: "${{ github.workspace }}/artifacts/"
