name: Newman Test Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Newman and htmlextra reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Create Newman report directory
        run: mkdir -p "${{ github.workspace }}/newman"

      - name: Run API tests with Newman
        run: |
          echo "Looking for files in ${GITHUB_WORKSPACE}/postman/collections"
          echo "Looking for environment files in ${GITHUB_WORKSPACE}/postman/environments"
          for collection_file in "${GITHUB_WORKSPACE}/postman/collections/"*.json; do
            if [ -f "$collection_file" ]; then
              collection_name=$(basename "$collection_file" .json)
              echo "Running tests for $collection_file"
              
              # Find corresponding environment file
              environment_file="${GITHUB_WORKSPACE}/postman/environments/${collection_name}.json"
              if [ -f "$environment_file" ]; then
                echo "Using environment file $environment_file"
                newman run "$collection_file" \
                  --environment "$environment_file" \
                  --reporters cli,htmlextra,json \
                  --reporter-htmlextra-export "${{ github.workspace }}/newman/report-${collection_name}.html" \
                  --reporter-json-export "${{ github.workspace }}/newman/report-${collection_name}.json"
              else
                echo "No environment file found for $collection_file"
                newman run "$collection_file" \
                  --reporters cli,htmlextra,json \
                  --reporter-htmlextra-export "${{ github.workspace }}/newman/report-${collection_name}.html" \
                  --reporter-json-export "${{ github.workspace }}/newman/report-${collection_name}.json"
              fi
            else
              echo "No JSON files found in ${GITHUB_WORKSPACE}/postman/collections"
            fi
          done

      - name: Upload Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: "${{ github.workspace }}/newman/"
