name: Newman Test Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Newman and htmlextra reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Create Newman report directory
        run: mkdir -p newman

      - name: Run API tests with Newman
        run: |
          newman run "${{ github.workspace }}/postman/collections/UsersAPI.json" \
            --reporters cli,htmlextra,json \
            --reporter-htmlextra-export "${{ github.workspace }}/newman/report.html" \
            --reporter-json-export "${{ github.workspace }}/newman/report.json"

      - name: List files for debugging
        run: ls -R ${{ github.workspace }}/newman

      - name: Upload Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: ${{ github.workspace }}/newman/